#!/usr/bin/env python

import math

for j in range(10):
    sum = 0;
    for i in range(2):
        t1 = int(input("t1: "))
        t2 = int(input("t2: "))
        k1 = int(input("k1: "))
        k2 = int(input("k2: "))
        b = float(format(float (2 * math.pi *(t2*k1 - k2*t1)) / float((pow(t1, 2) * t2 - pow(t2, 2) * t1)), '.6f'))
        print(b)
        sum += b

    print(sum/4);
    if  j % 2 == 0:
        sum2 = sum
    else :
        print("请输入B的值:")
        m = int(input("m:"))
        I = float(m * (9.794 - 0.02 *sum) *0.02) / float(sum - sum2)
        print(I);
